[package]
name = "nes_emu_rust"
version = "0.1.0"
authors = ["Mita <martin.pelletier78@hotmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.0"
lazy_static = "1.4.0"

[dependencies.sdl2]
version = "0.32"
features = ["unsafe_textures"]